sonar.projectKey=Berkilic41_task-tracker
sonar.organization=berkilic41
sonar.projectName=Task Tracker
sonar.projectVersion=1.0

sonar.sources=TaskTracker
sonar.tests=tests
sonar.exclusions=**/obj/**,**/bin/**

sonar.cs.opencover.reportsPaths=**/coverage.opencover.xml
sonar.cs.vstest.reportsPaths=**/test-results.trx
