-- =============================================================
-- Task Tracker Seed Data
-- Migration: 002_SeedData
-- Optional: run after 001_InitialSchema to populate sample data.
-- Passwords below are all: P@ssw0rd
-- (PBKDF2-SHA256, 100 000 iterations — generated by the app)
-- To generate real hashes run the app and register users instead.
-- =============================================================

USE TaskTrackerDb;
GO

-- Sample users (insert only when table is empty)
IF NOT EXISTS (SELECT 1 FROM Users)
BEGIN
    -- Use the app's Register page to create real users with properly hashed passwords.
    -- The rows below use a placeholder hash; replace with real hashes from the app.
    INSERT INTO Users (Username, Email, PasswordHash, CreatedAt) VALUES
        ('alice',   'alice@example.com',   'PLACEHOLDER_HASH', GETUTCDATE()),
        ('bob',     'bob@example.com',     'PLACEHOLDER_HASH', GETUTCDATE()),
        ('charlie', 'charlie@example.com', 'PLACEHOLDER_HASH', GETUTCDATE());
END
GO

-- Sample tasks (insert only when table is empty)
IF NOT EXISTS (SELECT 1 FROM Tasks)
BEGIN
    DECLARE @Alice   INT = (SELECT Id FROM Users WHERE Username = 'alice');
    DECLARE @Bob     INT = (SELECT Id FROM Users WHERE Username = 'bob');
    DECLARE @Charlie INT = (SELECT Id FROM Users WHERE Username = 'charlie');

    INSERT INTO Tasks (Title, Description, Status, Priority, DueDate, CreatedByUserId, AssignedToUserId) VALUES
        ('Set up CI/CD pipeline',        'Configure GitHub Actions for build and deploy.', 1, 2, DATEADD(day,  7, GETUTCDATE()), @Alice,   @Bob),
        ('Write unit tests',             'Cover all repository methods with xUnit tests.', 0, 1, DATEADD(day, 14, GETUTCDATE()), @Alice,   @Alice),
        ('Design landing page',          'Create wireframes and implement Bootstrap UI.',  0, 1, DATEADD(day, 10, GETUTCDATE()), @Bob,     @Charlie),
        ('Fix login redirect bug',       'After login, user is redirected to /Home.',      2, 2, DATEADD(day, -1, GETUTCDATE()), @Bob,     @Bob),
        ('Write API documentation',      NULL,                                             0, 0, NULL,                           @Charlie, NULL),
        ('Refactor repository layer',    'Extract shared connection logic.',               1, 1, DATEADD(day,  5, GETUTCDATE()), @Charlie, @Alice);
END
GO

PRINT 'Seed data inserted.';
GO
